#!/usr/bin/env python3
"""Patch FRB 2.12.0's bundled CargoKit Gradle script for Gradle 9.

Gradle 9 removed Project.exec. CargoKit generated by FRB 2.12.0 still uses it.
This patch injects ExecOperations into CargoKitBuildTask and replaces project.exec.
The operation is idempotent and fails loudly if the expected template is absent.
"""
from __future__ import annotations

from pathlib import Path
import re
import sys

path = Path("rust_builder/cargokit/gradle/plugin.gradle")
if not path.is_file():
    print(f"ERROR: CargoKit Gradle plugin not found: {path}", file=sys.stderr)
    print("Run `make integrate` first.", file=sys.stderr)
    raise SystemExit(1)

text = path.read_text(encoding="utf-8")

original = text

# Repair malformed output from patch v5 before deciding the file is already patched.
text = re.sub(
    r"\b(?:abstract\s+){2,}(class\s+CargoKitBuildTask\s+extends\s+DefaultTask\s*\{)",
    r"abstract \1",
    text,
)

if (
    "abstract ExecOperations getExecOperations()" in text
    and "project.exec {" not in text
):
    if text != original:
        path.write_text(text, encoding="utf-8")
        print(f"[PixelCraft] Repaired duplicate abstract modifier: {path}")
    else:
        print(f"[PixelCraft] CargoKit Gradle 9 patch already applied: {path}")
    raise SystemExit(0)

# Add Gradle service injection imports near the existing import block.
imports = "import org.gradle.process.ExecOperations\nimport javax.inject.Inject\n"
if "import org.gradle.process.ExecOperations" not in text:
    first_class = text.find("\nclass ")
    first_abstract_class = text.find("\nabstract class ")
    candidates = [i for i in (first_class, first_abstract_class) if i >= 0]
    insert_at = min(candidates) if candidates else -1
    if insert_at < 0:
        print("ERROR: Could not locate CargoKit class declarations.", file=sys.stderr)
        raise SystemExit(1)
    text = text[:insert_at] + "\n" + imports + text[insert_at:]

# Normalize accidental duplicate modifiers left by an earlier patch version.
text = re.sub(
    r"\b(?:abstract\s+){2,}(class\s+CargoKitBuildTask\s+extends\s+DefaultTask\s*\{)",
    r"abstract \1",
    text,
)

# Match the whole declaration, not a substring inside "abstract class".
class_pattern = re.compile(
    r"(?m)^(?:abstract\s+)?class\s+CargoKitBuildTask\s+extends\s+DefaultTask\s*\{"
)
match = class_pattern.search(text)
if match is None:
    print("ERROR: Could not locate CargoKitBuildTask declaration.", file=sys.stderr)
    raise SystemExit(1)

new_class = "abstract class CargoKitBuildTask extends DefaultTask {"
text = text[:match.start()] + new_class + text[match.end():]

marker = new_class
inject = """

    // Gradle 9 replacement for the removed Project.exec API.
    @Inject
    abstract ExecOperations getExecOperations()
"""
if marker in text and "abstract ExecOperations getExecOperations()" not in text:
    text = text.replace(marker, marker + inject, 1)

count = text.count("project.exec {")
if count == 0:
    print("ERROR: No project.exec calls found; CargoKit template may have changed.", file=sys.stderr)
    raise SystemExit(1)
text = text.replace("project.exec {", "execOperations.exec {")

if text == original:
    print("ERROR: CargoKit patch made no changes.", file=sys.stderr)
    raise SystemExit(1)

backup = path.with_suffix(".gradle.pre-gradle9")
if not backup.exists():
    backup.write_text(original, encoding="utf-8")
path.write_text(text, encoding="utf-8")

print(f"[PixelCraft] Patched {path} for Gradle 9 ({count} exec call(s)).")
print(f"[PixelCraft] Original backup: {backup}")
